package cmd

import "fmt"

func jimTribute() {
	fmt.Println(jim)

	fmt.Println(`
Grift was inspired by the Ruby program, Rake. (http://rake.rubyforge.org)

Rake was written by one of the kindest and generous people any tech community
was lucky to have, Jim Weirich.

We miss you Jim.

https://en.wikipedia.org/wiki/Jim_Weirich
`)
}

var jim = `
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD8MMMMMNMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8NOZNMMNMMDMMMMOMDMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMM8ZI+=$7+7+=?+~787?78MMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMM=?=Z?:+::::::,=~:::~~~===?$NMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMD==+~:~=~~=~::~=?=+?II?+~:::::NOMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNNN:,,~~:~:,:~:::+=I?$7$7I7I+=:~~?7ONNNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNDMZ,~:=.:,,.::,,:+?7777$77$$?I??~===IOMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMN+,,:::.,.:~+=:~==???I7IIIII???7+=~~~=$ZMDMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMDM7...:~+.~.:+=~~~~~==+++==++?+?I?+??~~::=:$DMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM8..,,~:,:,~~~~,,,::~++=~====++??I?==~~:::~,.+7OMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMO~::,,.,,,:,+~,,,,ZZ$?,~=+=+77???I??:~=.:::~~,,7NMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMI,~,...,,,,,~,?O==+~????II77~MOM=7I7~.~,,::~~::,~+MMMMMMMMMMMMMM
MMMMMMMMMMMMMMZ=~:..,~:,.~Z7=:~+.+7Z7?::~~+?7$8O7MII$.:~,,~~:,,,.,ONMMMMMMMMMMMM
MMMMMMMMMMMMMM,~..,~~Z$~$O7:=$8~,7$Z~$::+I8Z$Z$$ZO$$7+::,,,~:~:~.,.$NMMMMMMMMMMM
MMMMMMMMMMMMM$:,,:=+,,+III:8:~+I,7Z?=$7MD888=N88ZOZ$II=,,,~::::,:,..=MMMMMMMMMMM
MMMMMMMMMMMMM.,,+,,,:+I??I?=~,~77I$7:~~=II$?OD8D8$777I7~,:::~~~=::....MNMMMMMMMM
MMMMMMMMMMMM+.,?:~::~~?I$?Z$~+$$Z$+,:~,~ZZ~+I7I+??=??II?:~:~:,:~:,:,..:DMMMMMMMM
MMMMMMMMMMMD,++.7:=:=?O8Z7,:~+I$I=~:,,:~~~~===+I?III?7II7~~+~,,~~:,+...=MMMMMMMM
MMMMMMMMMMMN:.+?=:~7O7Z+?,=+$O7+?++:,.,,,:~+I7$Z$$$7$7$?$O=~+~:.,:~,~...MNMMMMMM
MMMMMMMMMMMD,,?IO~=O$=?7+?ZOOZDMMDOZ=~,,::~==+??ZZ$777$$7:+7~~=,.,:=,:,.~NMMMMMM
MMMMMMMMMMMM+,~I~==$I8:~+78$ZOOIZ$ZZD7~:::~=+?IIII7$77?III==~7~=~:,,.::.:$MMMMMM
MMMMMMMMMMMM=,~=:O?8~:~,$8ND~,~,~:++=?+~::~~?+?II??I=?$$7I$+=?Z=~:~::.~:.:MMMMMM
MMMMMMMMMMMN?:,=~=:,=.,~:,:~,::=~=~I++=:,,:=+?I7I?I?$I$Z7I??7IZ7:,.,::,.,:~7MMMM
MMMMMMMMMMMM?:.:~=,:,,,,:~~?,~O$?IZ7IIII+==~=I777$$7$IOOZ$+$?+7?+?:,,.:,.,8MMMMM
MMMMMMMMMMMMZ:.:~=:,,:,:~=I$O8DDD8DO$Z77Z:~?++I77+7$II7$$$Z?~?O7?=~,,,.,,.+MMMMM
MMMMMMMMMMMMM+,,~:,,,=~~+O8DNN8N87$OMDNZ+=?$7+?+II+=+?+$I+Z7?+7?II~~.,:=::.~MMMM
MMMMMMMMMMMMM?,,::,:~~+=$8DM?,,~=??7$$Z+~+~+$7+==,::~=~?+I7++=+~+I=~:?~7+,~.OMMM
MMMMMMMMMMMMM:,::~,+=+=IDI:,+I$I$?7I????+=?+~~=~:~=I==??==?~==+?+?7~:+I$7==:+MMM
MMMMMMMMMMMM.~::+~==~+IO~=+?I?$~,=+?I+~~:~:+I?++:=+~~++I?=:=??==????+=Z$I$=,88MM
MMMMMMMMMMMM,,,~~?~=+7$:===,+~+=++~+=+=~:~=+$??=~~~===+~?=~+++?~????D8OII$+~$NMM
MMMMMMMMMMMM::~~~~+=?$+~:,~==::=~~===:,=~+~~=777=I+,I?I??:?+?=I?+7~ZM8N$IO$?=NMM
MMMMMMMMMMMM,~~=+~+?7?~~=~~~~:,:~:,:~,=,=~~+I=Z7?==?$=I???==??=7?=I~?O7?I$I+~OMM
MMMMMMMMDMND?~:==I+~+=::~~~~:~,:==:,=,,=~++?~?ZO?I?I7II++?7~?=++==~~+7I+~77==DMM
MMMMMMMMMN$N?~+?~+:==:,::,~:::?~=~:,:~,~~$$Z+?$O$7$7?$?++??+=+=~++==7I$?=++~+MMM
MMMMMMMMNMDI=:~=,+:,::.,,:~::~?+~,:,:~~~+I7?+$ZZZ8Z7Z$?I$7=?+==~=~=~~?8$I?:~MMMM
MMMMMMMMMMN++~~+~:~:,:,:,::,+~=~::::~+?I?$7~O7O$8O?7O7???I++?==++++I+7ZI?=$MMMMM
MMMMMMMMMMD~~,::::~,,,,:,:,~?:+,::,:~??=$7O$Z8ZOOZ8D8IZI?7$I???I+??+7IZZIIMMMMMM
MMMMMMMMMNDI:,+:=~,:,:,:::,~:~~~~:~:??=IZ+ZO$D$O8DD87O$OZ$$III?I+++?$Z7ZZ$MMMMMM
MMMMMMMMMMD~,~?=:~,:,,~:::~~===~~~:+=$7$I+ZDOD8NMM7DZZZZZZZO$7?I??77Z8DNNMMMMMMM
MMMMMMMMMZ?:~:+:,:,::::~~:~??:~~??=7++77Z7ZN88NNNN8DZOOOO$O$$II$$ZZD8OOOMMMMMMMM
MMMMMMMMMMO+=+:=~~~,:~~~~=+:I=7$$???$7$8$OODNDMDDDZ88888ZOZO7$OO8DDDD8MMMMMMMMMM
MMMMMMMMMM8$~~:~++:::~:~~?+II7OZZZ?$?8Z88ZNDDN8NDDDD888ZDDODZZ8NNDDDDMMMMMMMMMMM
MMMMMMMMMMMMO7~~==I+=~~++=?+$$O8OOOOZ88O88D88OO8ODDD888O8DD8ONNNNNNMMMMMMMMMMMMM
MMMMMMMMMMMMMM~+=??I??~I7$$OD8$8OO7888OON88DON888888DODNDDNNNMMNNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMM+=+??7I7ODOOOOOO88OZ8OZODD8Z88OZ8DD8DNNNDNMNMMNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM+?+I$$777OZOOOO8Z??8O788O88DZDD8DNNNNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMN=Z77$$ZZZZ8O8OO8$Z$888OD8NNDNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMM$?7Z7ZOZOOOOOOOO8O88DDNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNZZ$ZZZOO8O888DDDDDNDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN8D888DNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
`
